name: Test Bug Report Form
description: Report a bug or issue with the project.
title: "[Bug]: "
labels: ["bug"]
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file this bug report!
        Please fill out the form below to help us resolve the issue.
  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: Provide a short title for the bug.
      placeholder: "Bug summary"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "A clear description of the issue."
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Steps to reproduce"
  - type: input
    id: step-1
    attributes:
      label: Step 1
      description: Describe the first step to reproduce the bug.
      placeholder: "Step 1"
  - type: input
    id: step-2
    attributes:
      label: Step 2
      description: Describe the second step to reproduce the bug.
      placeholder: "Step 2"
  - type: input
    id: step-3
    attributes:
      label: Step 3
      description: Describe the third step to reproduce the bug (if needed).
      placeholder: "Step 3"
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Expected behavior"
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What operating system and software are you using?
      options:
        - "macOS"
        - "Windows"
        - "Linux"
        - "Other"
    validations:
      required: true
  - type: input
    id: software-version
    attributes:
      label: Version of software
      description: Enter the version of the software you're using (if known).
      placeholder: "e.g. v1.2.3"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any additional context that could help us investigate the issue.